### ISSUE TITLE
Mistake in the MAP blog post

### ISSUE THREAD

**Issue by gield** [sdsawtelle/sdsawtelle.github.io#1]
In [this blogpost](http://sdsawtelle.github.io/blog/output/mean-average-precision-MAP-for-recommender-systems.html), you say:

> There is more subtletly here though! In each row I've bolded the P(k) term which came from the correct recommendation in the third slot. Notice it is larger when there have been more successes in front of it - that's because the precision of the kth subset is higher the more correct guesses you've had up to point k. Thus, AP rewards you for front-loading the recommendations that are most likely to be correct.

Sadly, this is not true. An incorrect recommendation has 0 as its precision@K, so a recommendation does not have any influence from the previous recommendations.

Is it possible to edit this blog post? I might make a PR myself if I find the time. Thanks!

**Comment by sdsawtelle** [comment]
Sorry for the delayed response Giel. Possibly we are working with slightly different definitions of some terms (or perhaps I just don't fully understand your comment). You mention that 
>An incorrect recommendation has 0 as its precision@K, so a recommendation does not have any influence from the previous recommendations.
> 
The definition I am working with of precision@K is the percentage of correct recommendations in the top K positions of the ranked list. So for instance a ranked result set of [1, 1, 0, 0, 1] even though it has an incorrect recommendation at the fourth position, still has a P(k=4)=1/2 rather than zero. See for instance these [Stanford lecture notes](https://web.stanford.edu/class/cs276/handouts/EvaluationNew-handout-6-per.pdf). It is true that this term will not be included in the MAP summation since the summation is only over the k values with correct results.
